
package com.amazonaws.fps.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AvailableBalances complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AvailableBalances">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DisburseBalance" type="{http://fps.amazonaws.com/doc/2008-09-17/}Amount"/>
 *         &lt;element name="RefundBalance" type="{http://fps.amazonaws.com/doc/2008-09-17/}Amount"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * Generated by AWS Code Generator
 * <p/>
 * Tue Sep 29 03:25:23 PDT 2009
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AvailableBalances", propOrder = {
    "disburseBalance",
    "refundBalance"
})
public class AvailableBalances {

    @XmlElement(name = "DisburseBalance", required = true)
    protected Amount disburseBalance;
    @XmlElement(name = "RefundBalance", required = true)
    protected Amount refundBalance;

    /**
     * Default constructor
     * 
     */
    public AvailableBalances() {
        super();
    }

    /**
     * Value constructor
     * 
     */
    public AvailableBalances(final Amount disburseBalance, final Amount refundBalance) {
        this.disburseBalance = disburseBalance;
        this.refundBalance = refundBalance;
    }

    /**
     * Gets the value of the disburseBalance property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getDisburseBalance() {
        return disburseBalance;
    }

    /**
     * Sets the value of the disburseBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setDisburseBalance(Amount value) {
        this.disburseBalance = value;
    }

    public boolean isSetDisburseBalance() {
        return (this.disburseBalance!= null);
    }

    /**
     * Gets the value of the refundBalance property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getRefundBalance() {
        return refundBalance;
    }

    /**
     * Sets the value of the refundBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setRefundBalance(Amount value) {
        this.refundBalance = value;
    }

    public boolean isSetRefundBalance() {
        return (this.refundBalance!= null);
    }

    /**
     * Sets the value of the DisburseBalance property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public AvailableBalances withDisburseBalance(Amount value) {
        setDisburseBalance(value);
        return this;
    }

    /**
     * Sets the value of the RefundBalance property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public AvailableBalances withRefundBalance(Amount value) {
        setRefundBalance(value);
        return this;
    }
    

    /**
     * 
     * XML fragment representation of this object
     * 
     * @return XML fragment for this object. Name for outer
     * tag expected to be set by calling method. This fragment
     * returns inner properties representation only
     */
    protected String toXMLFragment() {
        StringBuffer xml = new StringBuffer();
        if (isSetDisburseBalance()) {
            Amount  disburseBalance = getDisburseBalance();
            xml.append("<DisburseBalance>");
            xml.append(disburseBalance.toXMLFragment());
            xml.append("</DisburseBalance>");
        } 
        if (isSetRefundBalance()) {
            Amount  refundBalance = getRefundBalance();
            xml.append("<RefundBalance>");
            xml.append(refundBalance.toXMLFragment());
            xml.append("</RefundBalance>");
        } 
        return xml.toString();
    }

    /**
     * 
     * Escape XML special characters
     */
    private String escapeXML(String string) {
        StringBuffer sb = new StringBuffer();
        int length = string.length();
        for (int i = 0; i < length; ++i) {
            char c = string.charAt(i);
            switch (c) {
            case '&':
                sb.append("&amp;");
                break;
            case '<':
                sb.append("&lt;");
                break;
            case '>':
                sb.append("&gt;");
                break;
            case '\'':
                sb.append("&#039;");
                break;
            case '"':
                sb.append("&quot;");
                break;
            default:
                sb.append(c);
            }
        }
        return sb.toString();
    }



    /**
     *
     * JSON fragment representation of this object
     *
     * @return JSON fragment for this object. Name for outer
     * object expected to be set by calling method. This fragment
     * returns inner properties representation only
     *
     */
    protected String toJSONFragment() {
        StringBuffer json = new StringBuffer();
        boolean first = true;
        if (isSetDisburseBalance()) {
            if (!first) json.append(", ");
            json.append("\"DisburseBalance\" : {");
            Amount  disburseBalance = getDisburseBalance();


            json.append(disburseBalance.toJSONFragment());
            json.append("}");
            first = false;
        }
        if (isSetRefundBalance()) {
            if (!first) json.append(", ");
            json.append("\"RefundBalance\" : {");
            Amount  refundBalance = getRefundBalance();


            json.append(refundBalance.toJSONFragment());
            json.append("}");
            first = false;
        }
        return json.toString();
    }

    /**
     *
     * Quote JSON string
     */
    private String quoteJSON(String string) {
        StringBuffer sb = new StringBuffer();
        sb.append("\"");
        int length = string.length();
        for (int i = 0; i < length; ++i) {
            char c = string.charAt(i);
            switch (c) {
            case '"':
                sb.append("\\\"");
                break;
            case '\\':
                sb.append("\\\\");
                break;
            case '/':
                sb.append("\\/");
                break;
            case '\b':
                sb.append("\\b");
                break;
            case '\f':
                sb.append("\\f");
                break;
            case '\n':
                sb.append("\\n");
                break;
            case '\r':
                sb.append("\\r");
                break;
            case '\t':
                sb.append("\\t");
                break;
            default:
                if (c <  ' ') {
                    sb.append("\\u" + String.format("%03x", Integer.valueOf(c)));
                } else {
                sb.append(c);
            }
        }
        }
        sb.append("\"");
        return sb.toString();
    }


}
