
package com.amazonaws.fps.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SubscriptionId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RefundAmount" type="{http://fps.amazonaws.com/doc/2008-09-17/}Amount" minOccurs="0"/>
 *         &lt;element name="CallerReference" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CancelReason" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * Generated by AWS Code Generator
 * <p/>
 * Tue Sep 29 03:25:23 PDT 2009
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "subscriptionId",
    "refundAmount",
    "callerReference",
    "cancelReason"
})
@XmlRootElement(name = "CancelSubscriptionAndRefundRequest")
public class CancelSubscriptionAndRefundRequest {

    @XmlElement(name = "SubscriptionId")
    protected String subscriptionId;
    @XmlElement(name = "RefundAmount")
    protected Amount refundAmount;
    @XmlElement(name = "CallerReference")
    protected String callerReference;
    @XmlElement(name = "CancelReason")
    protected String cancelReason;

    /**
     * Default constructor
     * 
     */
    public CancelSubscriptionAndRefundRequest() {
        super();
    }

    /**
     * Value constructor
     * 
     */
    public CancelSubscriptionAndRefundRequest(final String subscriptionId, final Amount refundAmount, final String callerReference, final String cancelReason) {
        this.subscriptionId = subscriptionId;
        this.refundAmount = refundAmount;
        this.callerReference = callerReference;
        this.cancelReason = cancelReason;
    }

    /**
     * Gets the value of the subscriptionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubscriptionId() {
        return subscriptionId;
    }

    /**
     * Sets the value of the subscriptionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubscriptionId(String value) {
        this.subscriptionId = value;
    }

    public boolean isSetSubscriptionId() {
        return (this.subscriptionId!= null);
    }

    /**
     * Gets the value of the refundAmount property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getRefundAmount() {
        return refundAmount;
    }

    /**
     * Sets the value of the refundAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setRefundAmount(Amount value) {
        this.refundAmount = value;
    }

    public boolean isSetRefundAmount() {
        return (this.refundAmount!= null);
    }

    /**
     * Gets the value of the callerReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCallerReference() {
        return callerReference;
    }

    /**
     * Sets the value of the callerReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCallerReference(String value) {
        this.callerReference = value;
    }

    public boolean isSetCallerReference() {
        return (this.callerReference!= null);
    }

    /**
     * Gets the value of the cancelReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCancelReason() {
        return cancelReason;
    }

    /**
     * Sets the value of the cancelReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCancelReason(String value) {
        this.cancelReason = value;
    }

    public boolean isSetCancelReason() {
        return (this.cancelReason!= null);
    }

    /**
     * Sets the value of the SubscriptionId property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public CancelSubscriptionAndRefundRequest withSubscriptionId(String value) {
        setSubscriptionId(value);
        return this;
    }

    /**
     * Sets the value of the RefundAmount property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public CancelSubscriptionAndRefundRequest withRefundAmount(Amount value) {
        setRefundAmount(value);
        return this;
    }

    /**
     * Sets the value of the CallerReference property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public CancelSubscriptionAndRefundRequest withCallerReference(String value) {
        setCallerReference(value);
        return this;
    }

    /**
     * Sets the value of the CancelReason property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public CancelSubscriptionAndRefundRequest withCancelReason(String value) {
        setCancelReason(value);
        return this;
    }
    


    /**
     *
     * JSON fragment representation of this object
     *
     * @return JSON fragment for this object. Name for outer
     * object expected to be set by calling method. This fragment
     * returns inner properties representation only
     *
     */
    protected String toJSONFragment() {
        StringBuffer json = new StringBuffer();
        boolean first = true;
        if (isSetSubscriptionId()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("SubscriptionId"));
            json.append(" : ");
            json.append(quoteJSON(getSubscriptionId()));
            first = false;
        }
        if (isSetRefundAmount()) {
            if (!first) json.append(", ");
            json.append("\"RefundAmount\" : {");
            Amount  refundAmount = getRefundAmount();


            json.append(refundAmount.toJSONFragment());
            json.append("}");
            first = false;
        }
        if (isSetCallerReference()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("CallerReference"));
            json.append(" : ");
            json.append(quoteJSON(getCallerReference()));
            first = false;
        }
        if (isSetCancelReason()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("CancelReason"));
            json.append(" : ");
            json.append(quoteJSON(getCancelReason()));
            first = false;
        }
        return json.toString();
    }

    /**
     *
     * Quote JSON string
     */
    private String quoteJSON(String string) {
        StringBuffer sb = new StringBuffer();
        sb.append("\"");
        int length = string.length();
        for (int i = 0; i < length; ++i) {
            char c = string.charAt(i);
            switch (c) {
            case '"':
                sb.append("\\\"");
                break;
            case '\\':
                sb.append("\\\\");
                break;
            case '/':
                sb.append("\\/");
                break;
            case '\b':
                sb.append("\\b");
                break;
            case '\f':
                sb.append("\\f");
                break;
            case '\n':
                sb.append("\\n");
                break;
            case '\r':
                sb.append("\\r");
                break;
            case '\t':
                sb.append("\\t");
                break;
            default:
                if (c <  ' ') {
                    sb.append("\\u" + String.format("%03x", Integer.valueOf(c)));
                } else {
                sb.append(c);
            }
        }
        }
        sb.append("\"");
        return sb.toString();
    }


}
