
package com.amazonaws.fps.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DebtBalance complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DebtBalance">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AvailableBalance" type="{http://fps.amazonaws.com/doc/2008-09-17/}Amount"/>
 *         &lt;element name="PendingOutBalance" type="{http://fps.amazonaws.com/doc/2008-09-17/}Amount" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * Generated by AWS Code Generator
 * <p/>
 * Tue Sep 29 03:25:23 PDT 2009
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DebtBalance", propOrder = {
    "availableBalance",
    "pendingOutBalance"
})
public class DebtBalance {

    @XmlElement(name = "AvailableBalance", required = true)
    protected Amount availableBalance;
    @XmlElement(name = "PendingOutBalance")
    protected Amount pendingOutBalance;

    /**
     * Default constructor
     * 
     */
    public DebtBalance() {
        super();
    }

    /**
     * Value constructor
     * 
     */
    public DebtBalance(final Amount availableBalance, final Amount pendingOutBalance) {
        this.availableBalance = availableBalance;
        this.pendingOutBalance = pendingOutBalance;
    }

    /**
     * Gets the value of the availableBalance property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getAvailableBalance() {
        return availableBalance;
    }

    /**
     * Sets the value of the availableBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setAvailableBalance(Amount value) {
        this.availableBalance = value;
    }

    public boolean isSetAvailableBalance() {
        return (this.availableBalance!= null);
    }

    /**
     * Gets the value of the pendingOutBalance property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getPendingOutBalance() {
        return pendingOutBalance;
    }

    /**
     * Sets the value of the pendingOutBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setPendingOutBalance(Amount value) {
        this.pendingOutBalance = value;
    }

    public boolean isSetPendingOutBalance() {
        return (this.pendingOutBalance!= null);
    }

    /**
     * Sets the value of the AvailableBalance property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public DebtBalance withAvailableBalance(Amount value) {
        setAvailableBalance(value);
        return this;
    }

    /**
     * Sets the value of the PendingOutBalance property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public DebtBalance withPendingOutBalance(Amount value) {
        setPendingOutBalance(value);
        return this;
    }
    

    /**
     * 
     * XML fragment representation of this object
     * 
     * @return XML fragment for this object. Name for outer
     * tag expected to be set by calling method. This fragment
     * returns inner properties representation only
     */
    protected String toXMLFragment() {
        StringBuffer xml = new StringBuffer();
        if (isSetAvailableBalance()) {
            Amount  availableBalance = getAvailableBalance();
            xml.append("<AvailableBalance>");
            xml.append(availableBalance.toXMLFragment());
            xml.append("</AvailableBalance>");
        } 
        if (isSetPendingOutBalance()) {
            Amount  pendingOutBalance = getPendingOutBalance();
            xml.append("<PendingOutBalance>");
            xml.append(pendingOutBalance.toXMLFragment());
            xml.append("</PendingOutBalance>");
        } 
        return xml.toString();
    }

    /**
     * 
     * Escape XML special characters
     */
    private String escapeXML(String string) {
        StringBuffer sb = new StringBuffer();
        int length = string.length();
        for (int i = 0; i < length; ++i) {
            char c = string.charAt(i);
            switch (c) {
            case '&':
                sb.append("&amp;");
                break;
            case '<':
                sb.append("&lt;");
                break;
            case '>':
                sb.append("&gt;");
                break;
            case '\'':
                sb.append("&#039;");
                break;
            case '"':
                sb.append("&quot;");
                break;
            default:
                sb.append(c);
            }
        }
        return sb.toString();
    }



    /**
     *
     * JSON fragment representation of this object
     *
     * @return JSON fragment for this object. Name for outer
     * object expected to be set by calling method. This fragment
     * returns inner properties representation only
     *
     */
    protected String toJSONFragment() {
        StringBuffer json = new StringBuffer();
        boolean first = true;
        if (isSetAvailableBalance()) {
            if (!first) json.append(", ");
            json.append("\"AvailableBalance\" : {");
            Amount  availableBalance = getAvailableBalance();


            json.append(availableBalance.toJSONFragment());
            json.append("}");
            first = false;
        }
        if (isSetPendingOutBalance()) {
            if (!first) json.append(", ");
            json.append("\"PendingOutBalance\" : {");
            Amount  pendingOutBalance = getPendingOutBalance();


            json.append(pendingOutBalance.toJSONFragment());
            json.append("}");
            first = false;
        }
        return json.toString();
    }

    /**
     *
     * Quote JSON string
     */
    private String quoteJSON(String string) {
        StringBuffer sb = new StringBuffer();
        sb.append("\"");
        int length = string.length();
        for (int i = 0; i < length; ++i) {
            char c = string.charAt(i);
            switch (c) {
            case '"':
                sb.append("\\\"");
                break;
            case '\\':
                sb.append("\\\\");
                break;
            case '/':
                sb.append("\\/");
                break;
            case '\b':
                sb.append("\\b");
                break;
            case '\f':
                sb.append("\\f");
                break;
            case '\n':
                sb.append("\\n");
                break;
            case '\r':
                sb.append("\\r");
                break;
            case '\t':
                sb.append("\\t");
                break;
            default:
                if (c <  ' ') {
                    sb.append("\\u" + String.format("%03x", Integer.valueOf(c)));
                } else {
                sb.append(c);
            }
        }
        }
        sb.append("\"");
        return sb.toString();
    }


}
