
package com.amazonaws.fps.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TokenUsageLimits" type="{http://fps.amazonaws.com/doc/2008-09-17/}TokenUsageLimit" maxOccurs="3" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * Generated by AWS Code Generator
 * <p/>
 * Tue Sep 29 03:25:23 PDT 2009
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "tokenUsageLimits"
})
@XmlRootElement(name = "GetTokenUsageResult")
public class GetTokenUsageResult {

    @XmlElement(name = "TokenUsageLimits")
    protected List<TokenUsageLimit> tokenUsageLimits;

    /**
     * Default constructor
     * 
     */
    public GetTokenUsageResult() {
        super();
    }

    /**
     * Value constructor
     * 
     */
    public GetTokenUsageResult(final List<TokenUsageLimit> tokenUsageLimits) {
        this.tokenUsageLimits = tokenUsageLimits;
    }

    /**
     * Gets the value of the tokenUsageLimits property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tokenUsageLimits property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTokenUsageLimits().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TokenUsageLimit }
     * 
     * 
     */
    public List<TokenUsageLimit> getTokenUsageLimits() {
        if (tokenUsageLimits == null) {
            tokenUsageLimits = new ArrayList<TokenUsageLimit>();
        }
        return this.tokenUsageLimits;
    }

    public boolean isSetTokenUsageLimits() {
        return ((this.tokenUsageLimits!= null)&&(!this.tokenUsageLimits.isEmpty()));
    }

    public void unsetTokenUsageLimits() {
        this.tokenUsageLimits = null;
    }

    /**
     * Sets the value of the TokenUsageLimits property.
     * 
     * @param values
     * @return
     *     this instance
     */
    public GetTokenUsageResult withTokenUsageLimits(TokenUsageLimit... values) {
        for (TokenUsageLimit value: values) {
            getTokenUsageLimits().add(value);
        }
        return this;
    }

    /**
     * Sets the value of the tokenUsageLimits property.
     * 
     * @param tokenUsageLimits
     *     allowed object is
     *     {@link TokenUsageLimit }
     *     
     */
    public void setTokenUsageLimits(List<TokenUsageLimit> tokenUsageLimits) {
        this.tokenUsageLimits = tokenUsageLimits;
    }
    

    /**
     * 
     * XML fragment representation of this object
     * 
     * @return XML fragment for this object. Name for outer
     * tag expected to be set by calling method. This fragment
     * returns inner properties representation only
     */
    protected String toXMLFragment() {
        StringBuffer xml = new StringBuffer();
        java.util.List<TokenUsageLimit> tokenUsageLimitsList = getTokenUsageLimits();
        for (TokenUsageLimit tokenUsageLimits : tokenUsageLimitsList) {
            xml.append("<TokenUsageLimits>");
            xml.append(tokenUsageLimits.toXMLFragment());
            xml.append("</TokenUsageLimits>");
        }
        return xml.toString();
    }

    /**
     * 
     * Escape XML special characters
     */
    private String escapeXML(String string) {
        StringBuffer sb = new StringBuffer();
        int length = string.length();
        for (int i = 0; i < length; ++i) {
            char c = string.charAt(i);
            switch (c) {
            case '&':
                sb.append("&amp;");
                break;
            case '<':
                sb.append("&lt;");
                break;
            case '>':
                sb.append("&gt;");
                break;
            case '\'':
                sb.append("&#039;");
                break;
            case '"':
                sb.append("&quot;");
                break;
            default:
                sb.append(c);
            }
        }
        return sb.toString();
    }



    /**
     *
     * JSON fragment representation of this object
     *
     * @return JSON fragment for this object. Name for outer
     * object expected to be set by calling method. This fragment
     * returns inner properties representation only
     *
     */
    protected String toJSONFragment() {
        StringBuffer json = new StringBuffer();
        boolean first = true;
        if (isSetTokenUsageLimits()) {
            if (!first) json.append(", ");
            json.append("\"TokenUsageLimits\" : [");
            java.util.List<TokenUsageLimit> tokenUsageLimitsList = getTokenUsageLimits();
            int tokenUsageLimitsListIndex = 0;
            for (TokenUsageLimit tokenUsageLimits : tokenUsageLimitsList) {
                if (tokenUsageLimitsListIndex > 0) json.append(", ");
                json.append("{");
                json.append("");
                json.append(tokenUsageLimits.toJSONFragment());
                json.append("}");
                first = false;
                ++tokenUsageLimitsListIndex;
            }
            json.append("]");
        }
        return json.toString();
    }

    /**
     *
     * Quote JSON string
     */
    private String quoteJSON(String string) {
        StringBuffer sb = new StringBuffer();
        sb.append("\"");
        int length = string.length();
        for (int i = 0; i < length; ++i) {
            char c = string.charAt(i);
            switch (c) {
            case '"':
                sb.append("\\\"");
                break;
            case '\\':
                sb.append("\\\\");
                break;
            case '/':
                sb.append("\\/");
                break;
            case '\b':
                sb.append("\\b");
                break;
            case '\f':
                sb.append("\\f");
                break;
            case '\n':
                sb.append("\\n");
                break;
            case '\r':
                sb.append("\\r");
                break;
            case '\t':
                sb.append("\\t");
                break;
            default:
                if (c <  ' ') {
                    sb.append("\\u" + String.format("%03x", Integer.valueOf(c)));
                } else {
                sb.append(c);
            }
        }
        }
        sb.append("\"");
        return sb.toString();
    }


}
