
package com.amazonaws.fps.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://fps.amazonaws.com/doc/2008-09-17/}GetTotalPrepaidLiabilityResult" minOccurs="0"/>
 *         &lt;element ref="{http://fps.amazonaws.com/doc/2008-09-17/}ResponseMetadata"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * Generated by AWS Code Generator
 * <p/>
 * Tue Sep 29 03:25:23 PDT 2009
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "getTotalPrepaidLiabilityResult",
    "responseMetadata"
})
@XmlRootElement(name = "GetTotalPrepaidLiabilityResponse")
public class GetTotalPrepaidLiabilityResponse {

    @XmlElement(name = "GetTotalPrepaidLiabilityResult")
    protected GetTotalPrepaidLiabilityResult getTotalPrepaidLiabilityResult;
    @XmlElement(name = "ResponseMetadata", required = true)
    protected ResponseMetadata responseMetadata;

    /**
     * Default constructor
     * 
     */
    public GetTotalPrepaidLiabilityResponse() {
        super();
    }

    /**
     * Value constructor
     * 
     */
    public GetTotalPrepaidLiabilityResponse(final GetTotalPrepaidLiabilityResult getTotalPrepaidLiabilityResult, final ResponseMetadata responseMetadata) {
        this.getTotalPrepaidLiabilityResult = getTotalPrepaidLiabilityResult;
        this.responseMetadata = responseMetadata;
    }

    /**
     * Gets the value of the getTotalPrepaidLiabilityResult property.
     * 
     * @return
     *     possible object is
     *     {@link GetTotalPrepaidLiabilityResult }
     *     
     */
    public GetTotalPrepaidLiabilityResult getGetTotalPrepaidLiabilityResult() {
        return getTotalPrepaidLiabilityResult;
    }

    /**
     * Sets the value of the getTotalPrepaidLiabilityResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetTotalPrepaidLiabilityResult }
     *     
     */
    public void setGetTotalPrepaidLiabilityResult(GetTotalPrepaidLiabilityResult value) {
        this.getTotalPrepaidLiabilityResult = value;
    }

    public boolean isSetGetTotalPrepaidLiabilityResult() {
        return (this.getTotalPrepaidLiabilityResult!= null);
    }

    /**
     * Gets the value of the responseMetadata property.
     * 
     * @return
     *     possible object is
     *     {@link ResponseMetadata }
     *     
     */
    public ResponseMetadata getResponseMetadata() {
        return responseMetadata;
    }

    /**
     * Sets the value of the responseMetadata property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResponseMetadata }
     *     
     */
    public void setResponseMetadata(ResponseMetadata value) {
        this.responseMetadata = value;
    }

    public boolean isSetResponseMetadata() {
        return (this.responseMetadata!= null);
    }

    /**
     * Sets the value of the GetTotalPrepaidLiabilityResult property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public GetTotalPrepaidLiabilityResponse withGetTotalPrepaidLiabilityResult(GetTotalPrepaidLiabilityResult value) {
        setGetTotalPrepaidLiabilityResult(value);
        return this;
    }

    /**
     * Sets the value of the ResponseMetadata property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public GetTotalPrepaidLiabilityResponse withResponseMetadata(ResponseMetadata value) {
        setResponseMetadata(value);
        return this;
    }
    

    /**
     * 
     * XML string representation of this object
     * 
     * @return XML String
     */
    public String toXML() {
        StringBuffer xml = new StringBuffer();
        xml.append("<GetTotalPrepaidLiabilityResponse xmlns=\"http://fps.amazonaws.com/doc/2008-09-17/\">");
        if (isSetGetTotalPrepaidLiabilityResult()) {
            GetTotalPrepaidLiabilityResult  getTotalPrepaidLiabilityResult = getGetTotalPrepaidLiabilityResult();
            xml.append("<GetTotalPrepaidLiabilityResult>");
            xml.append(getTotalPrepaidLiabilityResult.toXMLFragment());
            xml.append("</GetTotalPrepaidLiabilityResult>");
        } 
        if (isSetResponseMetadata()) {
            ResponseMetadata  responseMetadata = getResponseMetadata();
            xml.append("<ResponseMetadata>");
            xml.append(responseMetadata.toXMLFragment());
            xml.append("</ResponseMetadata>");
        } 
        xml.append("</GetTotalPrepaidLiabilityResponse>");
        return xml.toString();
    }

    /**
     * 
     * Escape XML special characters
     */
    private String escapeXML(String string) {
        StringBuffer sb = new StringBuffer();
        int length = string.length();
        for (int i = 0; i < length; ++i) {
            char c = string.charAt(i);
            switch (c) {
            case '&':
                sb.append("&amp;");
                break;
            case '<':
                sb.append("&lt;");
                break;
            case '>':
                sb.append("&gt;");
                break;
            case '\'':
                sb.append("&#039;");
                break;
            case '"':
                sb.append("&quot;");
                break;
            default:
                sb.append(c);
            }
        }
        return sb.toString();
    }



    /**
     * 
     * JSON string representation of this object
     * 
     * @return JSON String
     */
    public String toJSON() {
        StringBuffer json = new StringBuffer();
        json.append("{\"GetTotalPrepaidLiabilityResponse\" : {");
        json.append(quoteJSON("@xmlns"));
        json.append(" : ");
        json.append(quoteJSON("http://fps.amazonaws.com/doc/2008-09-17/"));
        boolean first = true;
        json.append(", ");
        if (isSetGetTotalPrepaidLiabilityResult()) {
            if (!first) json.append(", ");
            json.append("\"GetTotalPrepaidLiabilityResult\" : {");
            GetTotalPrepaidLiabilityResult  getTotalPrepaidLiabilityResult = getGetTotalPrepaidLiabilityResult();

            json.append(getTotalPrepaidLiabilityResult.toJSONFragment());
            json.append("}");
            first = false;
        } 
        if (isSetResponseMetadata()) {
            if (!first) json.append(", ");
            json.append("\"ResponseMetadata\" : {");
            ResponseMetadata  responseMetadata = getResponseMetadata();

            json.append(responseMetadata.toJSONFragment());
            json.append("}");
            first = false;
        } 
        json.append("}");
        json.append("}");
        return json.toString();
    }

    /**
     * 
     * Quote JSON string
     */
    private String quoteJSON(String string) {
        StringBuffer sb = new StringBuffer();
        sb.append("\"");
        int length = string.length();
        for (int i = 0; i < length; ++i) {
            char c = string.charAt(i);
            switch (c) {
            case '"':
                sb.append("\\\"");
                break;
            case '\\':
                sb.append("\\\\");
                break;
            case '/':
                sb.append("\\/");
                break;
            case '\b':
                sb.append("\\b");
                break;
            case '\f':
                sb.append("\\f");
                break;
            case '\n':
                sb.append("\\n");
                break;
            case '\r':
                sb.append("\\r");
                break;
            case '\t':
                sb.append("\\t");
                break;
            default:
                if (c <  ' ') {
                    sb.append("\\u" + String.format("%03x", Integer.valueOf(c)));
                } else {
                sb.append(c);
                }
            }
        }
        sb.append("\"");
        return sb.toString();
    }


}
