
package com.amazonaws.fps.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://fps.amazonaws.com/doc/2008-09-17/}InstallPaymentInstructionResult" minOccurs="0"/>
 *         &lt;element ref="{http://fps.amazonaws.com/doc/2008-09-17/}ResponseMetadata"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * Generated by AWS Code Generator
 * <p/>
 * Tue Sep 29 03:25:23 PDT 2009
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "installPaymentInstructionResult",
    "responseMetadata"
})
@XmlRootElement(name = "InstallPaymentInstructionResponse")
public class InstallPaymentInstructionResponse {

    @XmlElement(name = "InstallPaymentInstructionResult")
    protected InstallPaymentInstructionResult installPaymentInstructionResult;
    @XmlElement(name = "ResponseMetadata", required = true)
    protected ResponseMetadata responseMetadata;

    /**
     * Default constructor
     * 
     */
    public InstallPaymentInstructionResponse() {
        super();
    }

    /**
     * Value constructor
     * 
     */
    public InstallPaymentInstructionResponse(final InstallPaymentInstructionResult installPaymentInstructionResult, final ResponseMetadata responseMetadata) {
        this.installPaymentInstructionResult = installPaymentInstructionResult;
        this.responseMetadata = responseMetadata;
    }

    /**
     * Gets the value of the installPaymentInstructionResult property.
     * 
     * @return
     *     possible object is
     *     {@link InstallPaymentInstructionResult }
     *     
     */
    public InstallPaymentInstructionResult getInstallPaymentInstructionResult() {
        return installPaymentInstructionResult;
    }

    /**
     * Sets the value of the installPaymentInstructionResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link InstallPaymentInstructionResult }
     *     
     */
    public void setInstallPaymentInstructionResult(InstallPaymentInstructionResult value) {
        this.installPaymentInstructionResult = value;
    }

    public boolean isSetInstallPaymentInstructionResult() {
        return (this.installPaymentInstructionResult!= null);
    }

    /**
     * Gets the value of the responseMetadata property.
     * 
     * @return
     *     possible object is
     *     {@link ResponseMetadata }
     *     
     */
    public ResponseMetadata getResponseMetadata() {
        return responseMetadata;
    }

    /**
     * Sets the value of the responseMetadata property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResponseMetadata }
     *     
     */
    public void setResponseMetadata(ResponseMetadata value) {
        this.responseMetadata = value;
    }

    public boolean isSetResponseMetadata() {
        return (this.responseMetadata!= null);
    }

    /**
     * Sets the value of the InstallPaymentInstructionResult property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public InstallPaymentInstructionResponse withInstallPaymentInstructionResult(InstallPaymentInstructionResult value) {
        setInstallPaymentInstructionResult(value);
        return this;
    }

    /**
     * Sets the value of the ResponseMetadata property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public InstallPaymentInstructionResponse withResponseMetadata(ResponseMetadata value) {
        setResponseMetadata(value);
        return this;
    }
    

    /**
     * 
     * XML string representation of this object
     * 
     * @return XML String
     */
    public String toXML() {
        StringBuffer xml = new StringBuffer();
        xml.append("<InstallPaymentInstructionResponse xmlns=\"http://fps.amazonaws.com/doc/2008-09-17/\">");
        if (isSetInstallPaymentInstructionResult()) {
            InstallPaymentInstructionResult  installPaymentInstructionResult = getInstallPaymentInstructionResult();
            xml.append("<InstallPaymentInstructionResult>");
            xml.append(installPaymentInstructionResult.toXMLFragment());
            xml.append("</InstallPaymentInstructionResult>");
        } 
        if (isSetResponseMetadata()) {
            ResponseMetadata  responseMetadata = getResponseMetadata();
            xml.append("<ResponseMetadata>");
            xml.append(responseMetadata.toXMLFragment());
            xml.append("</ResponseMetadata>");
        } 
        xml.append("</InstallPaymentInstructionResponse>");
        return xml.toString();
    }

    /**
     * 
     * Escape XML special characters
     */
    private String escapeXML(String string) {
        StringBuffer sb = new StringBuffer();
        int length = string.length();
        for (int i = 0; i < length; ++i) {
            char c = string.charAt(i);
            switch (c) {
            case '&':
                sb.append("&amp;");
                break;
            case '<':
                sb.append("&lt;");
                break;
            case '>':
                sb.append("&gt;");
                break;
            case '\'':
                sb.append("&#039;");
                break;
            case '"':
                sb.append("&quot;");
                break;
            default:
                sb.append(c);
            }
        }
        return sb.toString();
    }



    /**
     * 
     * JSON string representation of this object
     * 
     * @return JSON String
     */
    public String toJSON() {
        StringBuffer json = new StringBuffer();
        json.append("{\"InstallPaymentInstructionResponse\" : {");
        json.append(quoteJSON("@xmlns"));
        json.append(" : ");
        json.append(quoteJSON("http://fps.amazonaws.com/doc/2008-09-17/"));
        boolean first = true;
        json.append(", ");
        if (isSetInstallPaymentInstructionResult()) {
            if (!first) json.append(", ");
            json.append("\"InstallPaymentInstructionResult\" : {");
            InstallPaymentInstructionResult  installPaymentInstructionResult = getInstallPaymentInstructionResult();

            json.append(installPaymentInstructionResult.toJSONFragment());
            json.append("}");
            first = false;
        } 
        if (isSetResponseMetadata()) {
            if (!first) json.append(", ");
            json.append("\"ResponseMetadata\" : {");
            ResponseMetadata  responseMetadata = getResponseMetadata();

            json.append(responseMetadata.toJSONFragment());
            json.append("}");
            first = false;
        } 
        json.append("}");
        json.append("}");
        return json.toString();
    }

    /**
     * 
     * Quote JSON string
     */
    private String quoteJSON(String string) {
        StringBuffer sb = new StringBuffer();
        sb.append("\"");
        int length = string.length();
        for (int i = 0; i < length; ++i) {
            char c = string.charAt(i);
            switch (c) {
            case '"':
                sb.append("\\\"");
                break;
            case '\\':
                sb.append("\\\\");
                break;
            case '/':
                sb.append("\\/");
                break;
            case '\b':
                sb.append("\\b");
                break;
            case '\f':
                sb.append("\\f");
                break;
            case '\n':
                sb.append("\\n");
                break;
            case '\r':
                sb.append("\\r");
                break;
            case '\t':
                sb.append("\\t");
                break;
            default:
                if (c <  ' ') {
                    sb.append("\\u" + String.format("%03x", Integer.valueOf(c)));
                } else {
                sb.append(c);
                }
            }
        }
        sb.append("\"");
        return sb.toString();
    }


}
