
package com.amazonaws.fps.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TransactionId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RefundAmount" type="{http://fps.amazonaws.com/doc/2008-09-17/}Amount" minOccurs="0"/>
 *         &lt;element name="CallerReference" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CallerDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MarketplaceRefundPolicy" type="{http://fps.amazonaws.com/doc/2008-09-17/}MarketplaceRefundPolicy" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * Generated by AWS Code Generator
 * <p/>
 * Tue Sep 29 03:25:23 PDT 2009
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "transactionId",
    "refundAmount",
    "callerReference",
    "callerDescription",
    "marketplaceRefundPolicy"
})
@XmlRootElement(name = "RefundRequest")
public class RefundRequest {

    @XmlElement(name = "TransactionId")
    protected String transactionId;
    @XmlElement(name = "RefundAmount")
    protected Amount refundAmount;
    @XmlElement(name = "CallerReference")
    protected String callerReference;
    @XmlElement(name = "CallerDescription")
    protected String callerDescription;
    @XmlElement(name = "MarketplaceRefundPolicy", defaultValue = "MasterTxnOnly")
    protected MarketplaceRefundPolicy marketplaceRefundPolicy;

    /**
     * Default constructor
     * 
     */
    public RefundRequest() {
        super();
    }

    /**
     * Value constructor
     * 
     */
    public RefundRequest(final String transactionId, final Amount refundAmount, final String callerReference, final String callerDescription, final MarketplaceRefundPolicy marketplaceRefundPolicy) {
        this.transactionId = transactionId;
        this.refundAmount = refundAmount;
        this.callerReference = callerReference;
        this.callerDescription = callerDescription;
        this.marketplaceRefundPolicy = marketplaceRefundPolicy;
    }

    /**
     * Gets the value of the transactionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionId() {
        return transactionId;
    }

    /**
     * Sets the value of the transactionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionId(String value) {
        this.transactionId = value;
    }

    public boolean isSetTransactionId() {
        return (this.transactionId!= null);
    }

    /**
     * Gets the value of the refundAmount property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getRefundAmount() {
        return refundAmount;
    }

    /**
     * Sets the value of the refundAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setRefundAmount(Amount value) {
        this.refundAmount = value;
    }

    public boolean isSetRefundAmount() {
        return (this.refundAmount!= null);
    }

    /**
     * Gets the value of the callerReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCallerReference() {
        return callerReference;
    }

    /**
     * Sets the value of the callerReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCallerReference(String value) {
        this.callerReference = value;
    }

    public boolean isSetCallerReference() {
        return (this.callerReference!= null);
    }

    /**
     * Gets the value of the callerDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCallerDescription() {
        return callerDescription;
    }

    /**
     * Sets the value of the callerDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCallerDescription(String value) {
        this.callerDescription = value;
    }

    public boolean isSetCallerDescription() {
        return (this.callerDescription!= null);
    }

    /**
     * Gets the value of the marketplaceRefundPolicy property.
     * 
     * @return
     *     possible object is
     *     {@link MarketplaceRefundPolicy }
     *     
     */
    public MarketplaceRefundPolicy getMarketplaceRefundPolicy() {
        return marketplaceRefundPolicy;
    }

    /**
     * Sets the value of the marketplaceRefundPolicy property.
     * 
     * @param value
     *     allowed object is
     *     {@link MarketplaceRefundPolicy }
     *     
     */
    public void setMarketplaceRefundPolicy(MarketplaceRefundPolicy value) {
        this.marketplaceRefundPolicy = value;
    }

    public boolean isSetMarketplaceRefundPolicy() {
        return (this.marketplaceRefundPolicy!= null);
    }

    /**
     * Sets the value of the TransactionId property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public RefundRequest withTransactionId(String value) {
        setTransactionId(value);
        return this;
    }

    /**
     * Sets the value of the RefundAmount property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public RefundRequest withRefundAmount(Amount value) {
        setRefundAmount(value);
        return this;
    }

    /**
     * Sets the value of the CallerReference property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public RefundRequest withCallerReference(String value) {
        setCallerReference(value);
        return this;
    }

    /**
     * Sets the value of the CallerDescription property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public RefundRequest withCallerDescription(String value) {
        setCallerDescription(value);
        return this;
    }

    /**
     * Sets the value of the MarketplaceRefundPolicy property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public RefundRequest withMarketplaceRefundPolicy(MarketplaceRefundPolicy value) {
        setMarketplaceRefundPolicy(value);
        return this;
    }
    


    /**
     *
     * JSON fragment representation of this object
     *
     * @return JSON fragment for this object. Name for outer
     * object expected to be set by calling method. This fragment
     * returns inner properties representation only
     *
     */
    protected String toJSONFragment() {
        StringBuffer json = new StringBuffer();
        boolean first = true;
        if (isSetTransactionId()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("TransactionId"));
            json.append(" : ");
            json.append(quoteJSON(getTransactionId()));
            first = false;
        }
        if (isSetRefundAmount()) {
            if (!first) json.append(", ");
            json.append("\"RefundAmount\" : {");
            Amount  refundAmount = getRefundAmount();


            json.append(refundAmount.toJSONFragment());
            json.append("}");
            first = false;
        }
        if (isSetCallerReference()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("CallerReference"));
            json.append(" : ");
            json.append(quoteJSON(getCallerReference()));
            first = false;
        }
        if (isSetCallerDescription()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("CallerDescription"));
            json.append(" : ");
            json.append(quoteJSON(getCallerDescription()));
            first = false;
        }
        if (isSetMarketplaceRefundPolicy()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("MarketplaceRefundPolicy"));
            json.append(" : ");
            json.append(quoteJSON(getMarketplaceRefundPolicy().value()));
            first = false;
        }
        return json.toString();
    }

    /**
     *
     * Quote JSON string
     */
    private String quoteJSON(String string) {
        StringBuffer sb = new StringBuffer();
        sb.append("\"");
        int length = string.length();
        for (int i = 0; i < length; ++i) {
            char c = string.charAt(i);
            switch (c) {
            case '"':
                sb.append("\\\"");
                break;
            case '\\':
                sb.append("\\\\");
                break;
            case '/':
                sb.append("\\/");
                break;
            case '\b':
                sb.append("\\b");
                break;
            case '\f':
                sb.append("\\f");
                break;
            case '\n':
                sb.append("\\n");
                break;
            case '\r':
                sb.append("\\r");
                break;
            case '\t':
                sb.append("\\t");
                break;
            default:
                if (c <  ' ') {
                    sb.append("\\u" + String.format("%03x", Integer.valueOf(c)));
                } else {
                sb.append(c);
            }
        }
        }
        sb.append("\"");
        return sb.toString();
    }


}
