
package com.amazonaws.fps.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ReserveTransactionId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TransactionAmount" type="{http://fps.amazonaws.com/doc/2008-09-17/}Amount" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * Generated by AWS Code Generator
 * <p/>
 * Tue Sep 29 03:25:23 PDT 2009
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "reserveTransactionId",
    "transactionAmount"
})
@XmlRootElement(name = "SettleRequest")
public class SettleRequest {

    @XmlElement(name = "ReserveTransactionId")
    protected String reserveTransactionId;
    @XmlElement(name = "TransactionAmount")
    protected Amount transactionAmount;

    /**
     * Default constructor
     * 
     */
    public SettleRequest() {
        super();
    }

    /**
     * Value constructor
     * 
     */
    public SettleRequest(final String reserveTransactionId, final Amount transactionAmount) {
        this.reserveTransactionId = reserveTransactionId;
        this.transactionAmount = transactionAmount;
    }

    /**
     * Gets the value of the reserveTransactionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReserveTransactionId() {
        return reserveTransactionId;
    }

    /**
     * Sets the value of the reserveTransactionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReserveTransactionId(String value) {
        this.reserveTransactionId = value;
    }

    public boolean isSetReserveTransactionId() {
        return (this.reserveTransactionId!= null);
    }

    /**
     * Gets the value of the transactionAmount property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getTransactionAmount() {
        return transactionAmount;
    }

    /**
     * Sets the value of the transactionAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setTransactionAmount(Amount value) {
        this.transactionAmount = value;
    }

    public boolean isSetTransactionAmount() {
        return (this.transactionAmount!= null);
    }

    /**
     * Sets the value of the ReserveTransactionId property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public SettleRequest withReserveTransactionId(String value) {
        setReserveTransactionId(value);
        return this;
    }

    /**
     * Sets the value of the TransactionAmount property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public SettleRequest withTransactionAmount(Amount value) {
        setTransactionAmount(value);
        return this;
    }
    


    /**
     *
     * JSON fragment representation of this object
     *
     * @return JSON fragment for this object. Name for outer
     * object expected to be set by calling method. This fragment
     * returns inner properties representation only
     *
     */
    protected String toJSONFragment() {
        StringBuffer json = new StringBuffer();
        boolean first = true;
        if (isSetReserveTransactionId()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("ReserveTransactionId"));
            json.append(" : ");
            json.append(quoteJSON(getReserveTransactionId()));
            first = false;
        }
        if (isSetTransactionAmount()) {
            if (!first) json.append(", ");
            json.append("\"TransactionAmount\" : {");
            Amount  transactionAmount = getTransactionAmount();


            json.append(transactionAmount.toJSONFragment());
            json.append("}");
            first = false;
        }
        return json.toString();
    }

    /**
     *
     * Quote JSON string
     */
    private String quoteJSON(String string) {
        StringBuffer sb = new StringBuffer();
        sb.append("\"");
        int length = string.length();
        for (int i = 0; i < length; ++i) {
            char c = string.charAt(i);
            switch (c) {
            case '"':
                sb.append("\\\"");
                break;
            case '\\':
                sb.append("\\\\");
                break;
            case '/':
                sb.append("\\/");
                break;
            case '\b':
                sb.append("\\b");
                break;
            case '\f':
                sb.append("\\f");
                break;
            case '\n':
                sb.append("\\n");
                break;
            case '\r':
                sb.append("\\r");
                break;
            case '\t':
                sb.append("\\t");
                break;
            default:
                if (c <  ' ') {
                    sb.append("\\u" + String.format("%03x", Integer.valueOf(c)));
                } else {
                sb.append(c);
            }
        }
        }
        sb.append("\"");
        return sb.toString();
    }


}
