
package com.amazonaws.fps.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for StatusHistory complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StatusHistory">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Date" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="TransactionStatus" type="{http://fps.amazonaws.com/doc/2008-09-17/}TransactionStatus"/>
 *         &lt;element name="StatusCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Amount" type="{http://fps.amazonaws.com/doc/2008-09-17/}Amount"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * Generated by AWS Code Generator
 * <p/>
 * Tue Sep 29 03:25:23 PDT 2009
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StatusHistory", propOrder = {
    "date",
    "transactionStatus",
    "statusCode",
    "amount"
})
public class StatusHistory {

    @XmlElement(name = "Date", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar date;
    @XmlElement(name = "TransactionStatus", required = true)
    protected TransactionStatus transactionStatus;
    @XmlElement(name = "StatusCode")
    protected String statusCode;
    @XmlElement(name = "Amount", required = true)
    protected Amount amount;

    /**
     * Default constructor
     * 
     */
    public StatusHistory() {
        super();
    }

    /**
     * Value constructor
     * 
     */
    public StatusHistory(final XMLGregorianCalendar date, final TransactionStatus transactionStatus, final String statusCode, final Amount amount) {
        this.date = date;
        this.transactionStatus = transactionStatus;
        this.statusCode = statusCode;
        this.amount = amount;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDate(XMLGregorianCalendar value) {
        this.date = value;
    }

    public boolean isSetDate() {
        return (this.date!= null);
    }

    /**
     * Gets the value of the transactionStatus property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionStatus }
     *     
     */
    public TransactionStatus getTransactionStatus() {
        return transactionStatus;
    }

    /**
     * Sets the value of the transactionStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionStatus }
     *     
     */
    public void setTransactionStatus(TransactionStatus value) {
        this.transactionStatus = value;
    }

    public boolean isSetTransactionStatus() {
        return (this.transactionStatus!= null);
    }

    /**
     * Gets the value of the statusCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatusCode() {
        return statusCode;
    }

    /**
     * Sets the value of the statusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatusCode(String value) {
        this.statusCode = value;
    }

    public boolean isSetStatusCode() {
        return (this.statusCode!= null);
    }

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setAmount(Amount value) {
        this.amount = value;
    }

    public boolean isSetAmount() {
        return (this.amount!= null);
    }

    /**
     * Sets the value of the Date property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public StatusHistory withDate(XMLGregorianCalendar value) {
        setDate(value);
        return this;
    }

    /**
     * Sets the value of the TransactionStatus property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public StatusHistory withTransactionStatus(TransactionStatus value) {
        setTransactionStatus(value);
        return this;
    }

    /**
     * Sets the value of the StatusCode property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public StatusHistory withStatusCode(String value) {
        setStatusCode(value);
        return this;
    }

    /**
     * Sets the value of the Amount property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public StatusHistory withAmount(Amount value) {
        setAmount(value);
        return this;
    }
    

    /**
     * 
     * XML fragment representation of this object
     * 
     * @return XML fragment for this object. Name for outer
     * tag expected to be set by calling method. This fragment
     * returns inner properties representation only
     */
    protected String toXMLFragment() {
        StringBuffer xml = new StringBuffer();
        if (isSetDate()) {
            xml.append("<Date>");
            xml.append(getDate() + "");
            xml.append("</Date>");
        }
        if (isSetTransactionStatus()) {
            xml.append("<TransactionStatus>");
            xml.append(getTransactionStatus().value());
            xml.append("</TransactionStatus>");
        }
        if (isSetStatusCode()) {
            xml.append("<StatusCode>");
            xml.append(escapeXML(getStatusCode()));
            xml.append("</StatusCode>");
        }
        if (isSetAmount()) {
            Amount  amount = getAmount();
            xml.append("<Amount>");
            xml.append(amount.toXMLFragment());
            xml.append("</Amount>");
        } 
        return xml.toString();
    }

    /**
     * 
     * Escape XML special characters
     */
    private String escapeXML(String string) {
        StringBuffer sb = new StringBuffer();
        int length = string.length();
        for (int i = 0; i < length; ++i) {
            char c = string.charAt(i);
            switch (c) {
            case '&':
                sb.append("&amp;");
                break;
            case '<':
                sb.append("&lt;");
                break;
            case '>':
                sb.append("&gt;");
                break;
            case '\'':
                sb.append("&#039;");
                break;
            case '"':
                sb.append("&quot;");
                break;
            default:
                sb.append(c);
            }
        }
        return sb.toString();
    }



    /**
     *
     * JSON fragment representation of this object
     *
     * @return JSON fragment for this object. Name for outer
     * object expected to be set by calling method. This fragment
     * returns inner properties representation only
     *
     */
    protected String toJSONFragment() {
        StringBuffer json = new StringBuffer();
        boolean first = true;
        if (isSetDate()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("Date"));
            json.append(" : ");
            json.append(quoteJSON(getDate() + ""));
            first = false;
        }
        if (isSetTransactionStatus()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("TransactionStatus"));
            json.append(" : ");
            json.append(quoteJSON(getTransactionStatus().value()));
            first = false;
        }
        if (isSetStatusCode()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("StatusCode"));
            json.append(" : ");
            json.append(quoteJSON(getStatusCode()));
            first = false;
        }
        if (isSetAmount()) {
            if (!first) json.append(", ");
            json.append("\"Amount\" : {");
            Amount  amount = getAmount();


            json.append(amount.toJSONFragment());
            json.append("}");
            first = false;
        }
        return json.toString();
    }

    /**
     *
     * Quote JSON string
     */
    private String quoteJSON(String string) {
        StringBuffer sb = new StringBuffer();
        sb.append("\"");
        int length = string.length();
        for (int i = 0; i < length; ++i) {
            char c = string.charAt(i);
            switch (c) {
            case '"':
                sb.append("\\\"");
                break;
            case '\\':
                sb.append("\\\\");
                break;
            case '/':
                sb.append("\\/");
                break;
            case '\b':
                sb.append("\\b");
                break;
            case '\f':
                sb.append("\\f");
                break;
            case '\n':
                sb.append("\\n");
                break;
            case '\r':
                sb.append("\\r");
                break;
            case '\t':
                sb.append("\\t");
                break;
            default:
                if (c <  ' ') {
                    sb.append("\\u" + String.format("%03x", Integer.valueOf(c)));
                } else {
                sb.append(c);
            }
        }
        }
        sb.append("\"");
        return sb.toString();
    }


}
