
package com.amazonaws.fps.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for TransactionDetail complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TransactionDetail">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TransactionId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CallerReference" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CallerDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SenderDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DateReceived" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="DateCompleted" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="TransactionAmount" type="{http://fps.amazonaws.com/doc/2008-09-17/}Amount"/>
 *         &lt;element name="FPSFees" type="{http://fps.amazonaws.com/doc/2008-09-17/}Amount"/>
 *         &lt;element name="MarketplaceFees" type="{http://fps.amazonaws.com/doc/2008-09-17/}Amount" minOccurs="0"/>
 *         &lt;element name="FPSFeesPaidBy" type="{http://fps.amazonaws.com/doc/2008-09-17/}TransactionalRole"/>
 *         &lt;element name="SenderTokenId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RecipientTokenId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PrepaidInstrumentId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CreditInstrumentId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FPSOperation" type="{http://fps.amazonaws.com/doc/2008-09-17/}FPSOperation"/>
 *         &lt;element name="PaymentMethod" type="{http://fps.amazonaws.com/doc/2008-09-17/}PaymentMethod"/>
 *         &lt;element name="TransactionStatus" type="{http://fps.amazonaws.com/doc/2008-09-17/}TransactionStatus"/>
 *         &lt;element name="StatusCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="StatusMessage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SenderName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SenderEmail" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CallerName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RecipientName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RecipientEmail" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RelatedTransaction" type="{http://fps.amazonaws.com/doc/2008-09-17/}RelatedTransaction" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="StatusHistory" type="{http://fps.amazonaws.com/doc/2008-09-17/}StatusHistory" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * Generated by AWS Code Generator
 * <p/>
 * Tue Sep 29 03:25:23 PDT 2009
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TransactionDetail", propOrder = {
    "transactionId",
    "callerReference",
    "callerDescription",
    "senderDescription",
    "dateReceived",
    "dateCompleted",
    "transactionAmount",
    "fpsFees",
    "marketplaceFees",
    "fpsFeesPaidBy",
    "senderTokenId",
    "recipientTokenId",
    "prepaidInstrumentId",
    "creditInstrumentId",
    "fpsOperation",
    "paymentMethod",
    "transactionStatus",
    "statusCode",
    "statusMessage",
    "senderName",
    "senderEmail",
    "callerName",
    "recipientName",
    "recipientEmail",
    "relatedTransaction",
    "statusHistory"
})
public class TransactionDetail {

    @XmlElement(name = "TransactionId", required = true)
    protected String transactionId;
    @XmlElement(name = "CallerReference", required = true)
    protected String callerReference;
    @XmlElement(name = "CallerDescription")
    protected String callerDescription;
    @XmlElement(name = "SenderDescription")
    protected String senderDescription;
    @XmlElement(name = "DateReceived", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dateReceived;
    @XmlElement(name = "DateCompleted")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dateCompleted;
    @XmlElement(name = "TransactionAmount", required = true)
    protected Amount transactionAmount;
    @XmlElement(name = "FPSFees", required = true)
    protected Amount fpsFees;
    @XmlElement(name = "MarketplaceFees")
    protected Amount marketplaceFees;
    @XmlElement(name = "FPSFeesPaidBy", required = true)
    protected TransactionalRole fpsFeesPaidBy;
    @XmlElement(name = "SenderTokenId")
    protected String senderTokenId;
    @XmlElement(name = "RecipientTokenId")
    protected String recipientTokenId;
    @XmlElement(name = "PrepaidInstrumentId")
    protected String prepaidInstrumentId;
    @XmlElement(name = "CreditInstrumentId")
    protected String creditInstrumentId;
    @XmlElement(name = "FPSOperation", required = true)
    protected FPSOperation fpsOperation;
    @XmlElement(name = "PaymentMethod", required = true)
    protected PaymentMethod paymentMethod;
    @XmlElement(name = "TransactionStatus", required = true)
    protected TransactionStatus transactionStatus;
    @XmlElement(name = "StatusCode")
    protected String statusCode;
    @XmlElement(name = "StatusMessage")
    protected String statusMessage;
    @XmlElement(name = "SenderName")
    protected String senderName;
    @XmlElement(name = "SenderEmail")
    protected String senderEmail;
    @XmlElement(name = "CallerName", required = true)
    protected String callerName;
    @XmlElement(name = "RecipientName")
    protected String recipientName;
    @XmlElement(name = "RecipientEmail")
    protected String recipientEmail;
    @XmlElement(name = "RelatedTransaction")
    protected List<RelatedTransaction> relatedTransaction;
    @XmlElement(name = "StatusHistory", required = true)
    protected List<StatusHistory> statusHistory;

    /**
     * Default constructor
     * 
     */
    public TransactionDetail() {
        super();
    }

    /**
     * Value constructor
     * 
     */
    public TransactionDetail(final String transactionId, final String callerReference, final String callerDescription, final String senderDescription, final XMLGregorianCalendar dateReceived, final XMLGregorianCalendar dateCompleted, final Amount transactionAmount, final Amount fpsFees, final Amount marketplaceFees, final TransactionalRole fpsFeesPaidBy, final String senderTokenId, final String recipientTokenId, final String prepaidInstrumentId, final String creditInstrumentId, final FPSOperation fpsOperation, final PaymentMethod paymentMethod, final TransactionStatus transactionStatus, final String statusCode, final String statusMessage, final String senderName, final String senderEmail, final String callerName, final String recipientName, final String recipientEmail, final List<RelatedTransaction> relatedTransaction, final List<StatusHistory> statusHistory) {
        this.transactionId = transactionId;
        this.callerReference = callerReference;
        this.callerDescription = callerDescription;
        this.senderDescription = senderDescription;
        this.dateReceived = dateReceived;
        this.dateCompleted = dateCompleted;
        this.transactionAmount = transactionAmount;
        this.fpsFees = fpsFees;
        this.marketplaceFees = marketplaceFees;
        this.fpsFeesPaidBy = fpsFeesPaidBy;
        this.senderTokenId = senderTokenId;
        this.recipientTokenId = recipientTokenId;
        this.prepaidInstrumentId = prepaidInstrumentId;
        this.creditInstrumentId = creditInstrumentId;
        this.fpsOperation = fpsOperation;
        this.paymentMethod = paymentMethod;
        this.transactionStatus = transactionStatus;
        this.statusCode = statusCode;
        this.statusMessage = statusMessage;
        this.senderName = senderName;
        this.senderEmail = senderEmail;
        this.callerName = callerName;
        this.recipientName = recipientName;
        this.recipientEmail = recipientEmail;
        this.relatedTransaction = relatedTransaction;
        this.statusHistory = statusHistory;
    }

    /**
     * Gets the value of the transactionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionId() {
        return transactionId;
    }

    /**
     * Sets the value of the transactionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionId(String value) {
        this.transactionId = value;
    }

    public boolean isSetTransactionId() {
        return (this.transactionId!= null);
    }

    /**
     * Gets the value of the callerReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCallerReference() {
        return callerReference;
    }

    /**
     * Sets the value of the callerReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCallerReference(String value) {
        this.callerReference = value;
    }

    public boolean isSetCallerReference() {
        return (this.callerReference!= null);
    }

    /**
     * Gets the value of the callerDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCallerDescription() {
        return callerDescription;
    }

    /**
     * Sets the value of the callerDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCallerDescription(String value) {
        this.callerDescription = value;
    }

    public boolean isSetCallerDescription() {
        return (this.callerDescription!= null);
    }

    /**
     * Gets the value of the senderDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSenderDescription() {
        return senderDescription;
    }

    /**
     * Sets the value of the senderDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSenderDescription(String value) {
        this.senderDescription = value;
    }

    public boolean isSetSenderDescription() {
        return (this.senderDescription!= null);
    }

    /**
     * Gets the value of the dateReceived property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateReceived() {
        return dateReceived;
    }

    /**
     * Sets the value of the dateReceived property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateReceived(XMLGregorianCalendar value) {
        this.dateReceived = value;
    }

    public boolean isSetDateReceived() {
        return (this.dateReceived!= null);
    }

    /**
     * Gets the value of the dateCompleted property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateCompleted() {
        return dateCompleted;
    }

    /**
     * Sets the value of the dateCompleted property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateCompleted(XMLGregorianCalendar value) {
        this.dateCompleted = value;
    }

    public boolean isSetDateCompleted() {
        return (this.dateCompleted!= null);
    }

    /**
     * Gets the value of the transactionAmount property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getTransactionAmount() {
        return transactionAmount;
    }

    /**
     * Sets the value of the transactionAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setTransactionAmount(Amount value) {
        this.transactionAmount = value;
    }

    public boolean isSetTransactionAmount() {
        return (this.transactionAmount!= null);
    }

    /**
     * Gets the value of the fpsFees property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getFPSFees() {
        return fpsFees;
    }

    /**
     * Sets the value of the fpsFees property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setFPSFees(Amount value) {
        this.fpsFees = value;
    }

    public boolean isSetFPSFees() {
        return (this.fpsFees!= null);
    }

    /**
     * Gets the value of the marketplaceFees property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getMarketplaceFees() {
        return marketplaceFees;
    }

    /**
     * Sets the value of the marketplaceFees property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setMarketplaceFees(Amount value) {
        this.marketplaceFees = value;
    }

    public boolean isSetMarketplaceFees() {
        return (this.marketplaceFees!= null);
    }

    /**
     * Gets the value of the fpsFeesPaidBy property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionalRole }
     *     
     */
    public TransactionalRole getFPSFeesPaidBy() {
        return fpsFeesPaidBy;
    }

    /**
     * Sets the value of the fpsFeesPaidBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionalRole }
     *     
     */
    public void setFPSFeesPaidBy(TransactionalRole value) {
        this.fpsFeesPaidBy = value;
    }

    public boolean isSetFPSFeesPaidBy() {
        return (this.fpsFeesPaidBy!= null);
    }

    /**
     * Gets the value of the senderTokenId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSenderTokenId() {
        return senderTokenId;
    }

    /**
     * Sets the value of the senderTokenId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSenderTokenId(String value) {
        this.senderTokenId = value;
    }

    public boolean isSetSenderTokenId() {
        return (this.senderTokenId!= null);
    }

    /**
     * Gets the value of the recipientTokenId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecipientTokenId() {
        return recipientTokenId;
    }

    /**
     * Sets the value of the recipientTokenId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecipientTokenId(String value) {
        this.recipientTokenId = value;
    }

    public boolean isSetRecipientTokenId() {
        return (this.recipientTokenId!= null);
    }

    /**
     * Gets the value of the prepaidInstrumentId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrepaidInstrumentId() {
        return prepaidInstrumentId;
    }

    /**
     * Sets the value of the prepaidInstrumentId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrepaidInstrumentId(String value) {
        this.prepaidInstrumentId = value;
    }

    public boolean isSetPrepaidInstrumentId() {
        return (this.prepaidInstrumentId!= null);
    }

    /**
     * Gets the value of the creditInstrumentId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreditInstrumentId() {
        return creditInstrumentId;
    }

    /**
     * Sets the value of the creditInstrumentId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreditInstrumentId(String value) {
        this.creditInstrumentId = value;
    }

    public boolean isSetCreditInstrumentId() {
        return (this.creditInstrumentId!= null);
    }

    /**
     * Gets the value of the fpsOperation property.
     * 
     * @return
     *     possible object is
     *     {@link FPSOperation }
     *     
     */
    public FPSOperation getFPSOperation() {
        return fpsOperation;
    }

    /**
     * Sets the value of the fpsOperation property.
     * 
     * @param value
     *     allowed object is
     *     {@link FPSOperation }
     *     
     */
    public void setFPSOperation(FPSOperation value) {
        this.fpsOperation = value;
    }

    public boolean isSetFPSOperation() {
        return (this.fpsOperation!= null);
    }

    /**
     * Gets the value of the paymentMethod property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentMethod }
     *     
     */
    public PaymentMethod getPaymentMethod() {
        return paymentMethod;
    }

    /**
     * Sets the value of the paymentMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentMethod }
     *     
     */
    public void setPaymentMethod(PaymentMethod value) {
        this.paymentMethod = value;
    }

    public boolean isSetPaymentMethod() {
        return (this.paymentMethod!= null);
    }

    /**
     * Gets the value of the transactionStatus property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionStatus }
     *     
     */
    public TransactionStatus getTransactionStatus() {
        return transactionStatus;
    }

    /**
     * Sets the value of the transactionStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionStatus }
     *     
     */
    public void setTransactionStatus(TransactionStatus value) {
        this.transactionStatus = value;
    }

    public boolean isSetTransactionStatus() {
        return (this.transactionStatus!= null);
    }

    /**
     * Gets the value of the statusCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatusCode() {
        return statusCode;
    }

    /**
     * Sets the value of the statusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatusCode(String value) {
        this.statusCode = value;
    }

    public boolean isSetStatusCode() {
        return (this.statusCode!= null);
    }

    /**
     * Gets the value of the statusMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatusMessage() {
        return statusMessage;
    }

    /**
     * Sets the value of the statusMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatusMessage(String value) {
        this.statusMessage = value;
    }

    public boolean isSetStatusMessage() {
        return (this.statusMessage!= null);
    }

    /**
     * Gets the value of the senderName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSenderName() {
        return senderName;
    }

    /**
     * Sets the value of the senderName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSenderName(String value) {
        this.senderName = value;
    }

    public boolean isSetSenderName() {
        return (this.senderName!= null);
    }

    /**
     * Gets the value of the senderEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSenderEmail() {
        return senderEmail;
    }

    /**
     * Sets the value of the senderEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSenderEmail(String value) {
        this.senderEmail = value;
    }

    public boolean isSetSenderEmail() {
        return (this.senderEmail!= null);
    }

    /**
     * Gets the value of the callerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCallerName() {
        return callerName;
    }

    /**
     * Sets the value of the callerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCallerName(String value) {
        this.callerName = value;
    }

    public boolean isSetCallerName() {
        return (this.callerName!= null);
    }

    /**
     * Gets the value of the recipientName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecipientName() {
        return recipientName;
    }

    /**
     * Sets the value of the recipientName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecipientName(String value) {
        this.recipientName = value;
    }

    public boolean isSetRecipientName() {
        return (this.recipientName!= null);
    }

    /**
     * Gets the value of the recipientEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecipientEmail() {
        return recipientEmail;
    }

    /**
     * Sets the value of the recipientEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecipientEmail(String value) {
        this.recipientEmail = value;
    }

    public boolean isSetRecipientEmail() {
        return (this.recipientEmail!= null);
    }

    /**
     * Gets the value of the relatedTransaction property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the relatedTransaction property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRelatedTransaction().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RelatedTransaction }
     * 
     * 
     */
    public List<RelatedTransaction> getRelatedTransaction() {
        if (relatedTransaction == null) {
            relatedTransaction = new ArrayList<RelatedTransaction>();
        }
        return this.relatedTransaction;
    }

    public boolean isSetRelatedTransaction() {
        return ((this.relatedTransaction!= null)&&(!this.relatedTransaction.isEmpty()));
    }

    public void unsetRelatedTransaction() {
        this.relatedTransaction = null;
    }

    /**
     * Gets the value of the statusHistory property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the statusHistory property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStatusHistory().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StatusHistory }
     * 
     * 
     */
    public List<StatusHistory> getStatusHistory() {
        if (statusHistory == null) {
            statusHistory = new ArrayList<StatusHistory>();
        }
        return this.statusHistory;
    }

    public boolean isSetStatusHistory() {
        return ((this.statusHistory!= null)&&(!this.statusHistory.isEmpty()));
    }

    public void unsetStatusHistory() {
        this.statusHistory = null;
    }

    /**
     * Sets the value of the TransactionId property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public TransactionDetail withTransactionId(String value) {
        setTransactionId(value);
        return this;
    }

    /**
     * Sets the value of the CallerReference property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public TransactionDetail withCallerReference(String value) {
        setCallerReference(value);
        return this;
    }

    /**
     * Sets the value of the CallerDescription property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public TransactionDetail withCallerDescription(String value) {
        setCallerDescription(value);
        return this;
    }

    /**
     * Sets the value of the SenderDescription property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public TransactionDetail withSenderDescription(String value) {
        setSenderDescription(value);
        return this;
    }

    /**
     * Sets the value of the DateReceived property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public TransactionDetail withDateReceived(XMLGregorianCalendar value) {
        setDateReceived(value);
        return this;
    }

    /**
     * Sets the value of the DateCompleted property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public TransactionDetail withDateCompleted(XMLGregorianCalendar value) {
        setDateCompleted(value);
        return this;
    }

    /**
     * Sets the value of the TransactionAmount property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public TransactionDetail withTransactionAmount(Amount value) {
        setTransactionAmount(value);
        return this;
    }

    /**
     * Sets the value of the FPSFees property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public TransactionDetail withFPSFees(Amount value) {
        setFPSFees(value);
        return this;
    }

    /**
     * Sets the value of the MarketplaceFees property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public TransactionDetail withMarketplaceFees(Amount value) {
        setMarketplaceFees(value);
        return this;
    }

    /**
     * Sets the value of the FPSFeesPaidBy property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public TransactionDetail withFPSFeesPaidBy(TransactionalRole value) {
        setFPSFeesPaidBy(value);
        return this;
    }

    /**
     * Sets the value of the SenderTokenId property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public TransactionDetail withSenderTokenId(String value) {
        setSenderTokenId(value);
        return this;
    }

    /**
     * Sets the value of the RecipientTokenId property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public TransactionDetail withRecipientTokenId(String value) {
        setRecipientTokenId(value);
        return this;
    }

    /**
     * Sets the value of the PrepaidInstrumentId property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public TransactionDetail withPrepaidInstrumentId(String value) {
        setPrepaidInstrumentId(value);
        return this;
    }

    /**
     * Sets the value of the CreditInstrumentId property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public TransactionDetail withCreditInstrumentId(String value) {
        setCreditInstrumentId(value);
        return this;
    }

    /**
     * Sets the value of the FPSOperation property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public TransactionDetail withFPSOperation(FPSOperation value) {
        setFPSOperation(value);
        return this;
    }

    /**
     * Sets the value of the PaymentMethod property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public TransactionDetail withPaymentMethod(PaymentMethod value) {
        setPaymentMethod(value);
        return this;
    }

    /**
     * Sets the value of the TransactionStatus property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public TransactionDetail withTransactionStatus(TransactionStatus value) {
        setTransactionStatus(value);
        return this;
    }

    /**
     * Sets the value of the StatusCode property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public TransactionDetail withStatusCode(String value) {
        setStatusCode(value);
        return this;
    }

    /**
     * Sets the value of the StatusMessage property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public TransactionDetail withStatusMessage(String value) {
        setStatusMessage(value);
        return this;
    }

    /**
     * Sets the value of the SenderName property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public TransactionDetail withSenderName(String value) {
        setSenderName(value);
        return this;
    }

    /**
     * Sets the value of the SenderEmail property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public TransactionDetail withSenderEmail(String value) {
        setSenderEmail(value);
        return this;
    }

    /**
     * Sets the value of the CallerName property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public TransactionDetail withCallerName(String value) {
        setCallerName(value);
        return this;
    }

    /**
     * Sets the value of the RecipientName property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public TransactionDetail withRecipientName(String value) {
        setRecipientName(value);
        return this;
    }

    /**
     * Sets the value of the RecipientEmail property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public TransactionDetail withRecipientEmail(String value) {
        setRecipientEmail(value);
        return this;
    }

    /**
     * Sets the value of the RelatedTransaction property.
     * 
     * @param values
     * @return
     *     this instance
     */
    public TransactionDetail withRelatedTransaction(RelatedTransaction... values) {
        for (RelatedTransaction value: values) {
            getRelatedTransaction().add(value);
        }
        return this;
    }

    /**
     * Sets the value of the StatusHistory property.
     * 
     * @param values
     * @return
     *     this instance
     */
    public TransactionDetail withStatusHistory(StatusHistory... values) {
        for (StatusHistory value: values) {
            getStatusHistory().add(value);
        }
        return this;
    }

    /**
     * Sets the value of the relatedTransaction property.
     * 
     * @param relatedTransaction
     *     allowed object is
     *     {@link RelatedTransaction }
     *     
     */
    public void setRelatedTransaction(List<RelatedTransaction> relatedTransaction) {
        this.relatedTransaction = relatedTransaction;
    }

    /**
     * Sets the value of the statusHistory property.
     * 
     * @param statusHistory
     *     allowed object is
     *     {@link StatusHistory }
     *     
     */
    public void setStatusHistory(List<StatusHistory> statusHistory) {
        this.statusHistory = statusHistory;
    }
    

    /**
     * 
     * XML fragment representation of this object
     * 
     * @return XML fragment for this object. Name for outer
     * tag expected to be set by calling method. This fragment
     * returns inner properties representation only
     */
    protected String toXMLFragment() {
        StringBuffer xml = new StringBuffer();
        if (isSetTransactionId()) {
            xml.append("<TransactionId>");
            xml.append(escapeXML(getTransactionId()));
            xml.append("</TransactionId>");
        }
        if (isSetCallerReference()) {
            xml.append("<CallerReference>");
            xml.append(escapeXML(getCallerReference()));
            xml.append("</CallerReference>");
        }
        if (isSetCallerDescription()) {
            xml.append("<CallerDescription>");
            xml.append(escapeXML(getCallerDescription()));
            xml.append("</CallerDescription>");
        }
        if (isSetSenderDescription()) {
            xml.append("<SenderDescription>");
            xml.append(escapeXML(getSenderDescription()));
            xml.append("</SenderDescription>");
        }
        if (isSetDateReceived()) {
            xml.append("<DateReceived>");
            xml.append(getDateReceived() + "");
            xml.append("</DateReceived>");
        }
        if (isSetDateCompleted()) {
            xml.append("<DateCompleted>");
            xml.append(getDateCompleted() + "");
            xml.append("</DateCompleted>");
        }
        if (isSetTransactionAmount()) {
            Amount  transactionAmount = getTransactionAmount();
            xml.append("<TransactionAmount>");
            xml.append(transactionAmount.toXMLFragment());
            xml.append("</TransactionAmount>");
        } 
        if (isSetFPSFees()) {
            Amount  FPSFees = getFPSFees();
            xml.append("<FPSFees>");
            xml.append(FPSFees.toXMLFragment());
            xml.append("</FPSFees>");
        } 
        if (isSetMarketplaceFees()) {
            Amount  marketplaceFees = getMarketplaceFees();
            xml.append("<MarketplaceFees>");
            xml.append(marketplaceFees.toXMLFragment());
            xml.append("</MarketplaceFees>");
        } 
        if (isSetFPSFeesPaidBy()) {
            xml.append("<FPSFeesPaidBy>");
            xml.append(getFPSFeesPaidBy().value());
            xml.append("</FPSFeesPaidBy>");
        }
        if (isSetSenderTokenId()) {
            xml.append("<SenderTokenId>");
            xml.append(escapeXML(getSenderTokenId()));
            xml.append("</SenderTokenId>");
        }
        if (isSetRecipientTokenId()) {
            xml.append("<RecipientTokenId>");
            xml.append(escapeXML(getRecipientTokenId()));
            xml.append("</RecipientTokenId>");
        }
        if (isSetPrepaidInstrumentId()) {
            xml.append("<PrepaidInstrumentId>");
            xml.append(escapeXML(getPrepaidInstrumentId()));
            xml.append("</PrepaidInstrumentId>");
        }
        if (isSetCreditInstrumentId()) {
            xml.append("<CreditInstrumentId>");
            xml.append(escapeXML(getCreditInstrumentId()));
            xml.append("</CreditInstrumentId>");
        }
        if (isSetFPSOperation()) {
            xml.append("<FPSOperation>");
            xml.append(getFPSOperation().value());
            xml.append("</FPSOperation>");
        }
        if (isSetPaymentMethod()) {
            xml.append("<PaymentMethod>");
            xml.append(getPaymentMethod().value());
            xml.append("</PaymentMethod>");
        }
        if (isSetTransactionStatus()) {
            xml.append("<TransactionStatus>");
            xml.append(getTransactionStatus().value());
            xml.append("</TransactionStatus>");
        }
        if (isSetStatusCode()) {
            xml.append("<StatusCode>");
            xml.append(escapeXML(getStatusCode()));
            xml.append("</StatusCode>");
        }
        if (isSetStatusMessage()) {
            xml.append("<StatusMessage>");
            xml.append(escapeXML(getStatusMessage()));
            xml.append("</StatusMessage>");
        }
        if (isSetSenderName()) {
            xml.append("<SenderName>");
            xml.append(escapeXML(getSenderName()));
            xml.append("</SenderName>");
        }
        if (isSetSenderEmail()) {
            xml.append("<SenderEmail>");
            xml.append(escapeXML(getSenderEmail()));
            xml.append("</SenderEmail>");
        }
        if (isSetCallerName()) {
            xml.append("<CallerName>");
            xml.append(escapeXML(getCallerName()));
            xml.append("</CallerName>");
        }
        if (isSetRecipientName()) {
            xml.append("<RecipientName>");
            xml.append(escapeXML(getRecipientName()));
            xml.append("</RecipientName>");
        }
        if (isSetRecipientEmail()) {
            xml.append("<RecipientEmail>");
            xml.append(escapeXML(getRecipientEmail()));
            xml.append("</RecipientEmail>");
        }
        java.util.List<RelatedTransaction> relatedTransactionList = getRelatedTransaction();
        for (RelatedTransaction relatedTransaction : relatedTransactionList) {
            xml.append("<RelatedTransaction>");
            xml.append(relatedTransaction.toXMLFragment());
            xml.append("</RelatedTransaction>");
        }
        java.util.List<StatusHistory> statusHistoryList = getStatusHistory();
        for (StatusHistory statusHistory : statusHistoryList) {
            xml.append("<StatusHistory>");
            xml.append(statusHistory.toXMLFragment());
            xml.append("</StatusHistory>");
        }
        return xml.toString();
    }

    /**
     * 
     * Escape XML special characters
     */
    private String escapeXML(String string) {
        StringBuffer sb = new StringBuffer();
        int length = string.length();
        for (int i = 0; i < length; ++i) {
            char c = string.charAt(i);
            switch (c) {
            case '&':
                sb.append("&amp;");
                break;
            case '<':
                sb.append("&lt;");
                break;
            case '>':
                sb.append("&gt;");
                break;
            case '\'':
                sb.append("&#039;");
                break;
            case '"':
                sb.append("&quot;");
                break;
            default:
                sb.append(c);
            }
        }
        return sb.toString();
    }



    /**
     *
     * JSON fragment representation of this object
     *
     * @return JSON fragment for this object. Name for outer
     * object expected to be set by calling method. This fragment
     * returns inner properties representation only
     *
     */
    protected String toJSONFragment() {
        StringBuffer json = new StringBuffer();
        boolean first = true;
        if (isSetTransactionId()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("TransactionId"));
            json.append(" : ");
            json.append(quoteJSON(getTransactionId()));
            first = false;
        }
        if (isSetCallerReference()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("CallerReference"));
            json.append(" : ");
            json.append(quoteJSON(getCallerReference()));
            first = false;
        }
        if (isSetCallerDescription()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("CallerDescription"));
            json.append(" : ");
            json.append(quoteJSON(getCallerDescription()));
            first = false;
        }
        if (isSetSenderDescription()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("SenderDescription"));
            json.append(" : ");
            json.append(quoteJSON(getSenderDescription()));
            first = false;
        }
        if (isSetDateReceived()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("DateReceived"));
            json.append(" : ");
            json.append(quoteJSON(getDateReceived() + ""));
            first = false;
        }
        if (isSetDateCompleted()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("DateCompleted"));
            json.append(" : ");
            json.append(quoteJSON(getDateCompleted() + ""));
            first = false;
        }
        if (isSetTransactionAmount()) {
            if (!first) json.append(", ");
            json.append("\"TransactionAmount\" : {");
            Amount  transactionAmount = getTransactionAmount();


            json.append(transactionAmount.toJSONFragment());
            json.append("}");
            first = false;
        }
        if (isSetFPSFees()) {
            if (!first) json.append(", ");
            json.append("\"FPSFees\" : {");
            Amount  FPSFees = getFPSFees();


            json.append(FPSFees.toJSONFragment());
            json.append("}");
            first = false;
        }
        if (isSetMarketplaceFees()) {
            if (!first) json.append(", ");
            json.append("\"MarketplaceFees\" : {");
            Amount  marketplaceFees = getMarketplaceFees();


            json.append(marketplaceFees.toJSONFragment());
            json.append("}");
            first = false;
        }
        if (isSetFPSFeesPaidBy()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("FPSFeesPaidBy"));
            json.append(" : ");
            json.append(quoteJSON(getFPSFeesPaidBy().value()));
            first = false;
        }
        if (isSetSenderTokenId()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("SenderTokenId"));
            json.append(" : ");
            json.append(quoteJSON(getSenderTokenId()));
            first = false;
        }
        if (isSetRecipientTokenId()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("RecipientTokenId"));
            json.append(" : ");
            json.append(quoteJSON(getRecipientTokenId()));
            first = false;
        }
        if (isSetPrepaidInstrumentId()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("PrepaidInstrumentId"));
            json.append(" : ");
            json.append(quoteJSON(getPrepaidInstrumentId()));
            first = false;
        }
        if (isSetCreditInstrumentId()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("CreditInstrumentId"));
            json.append(" : ");
            json.append(quoteJSON(getCreditInstrumentId()));
            first = false;
        }
        if (isSetFPSOperation()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("FPSOperation"));
            json.append(" : ");
            json.append(quoteJSON(getFPSOperation().value()));
            first = false;
        }
        if (isSetPaymentMethod()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("PaymentMethod"));
            json.append(" : ");
            json.append(quoteJSON(getPaymentMethod().value()));
            first = false;
        }
        if (isSetTransactionStatus()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("TransactionStatus"));
            json.append(" : ");
            json.append(quoteJSON(getTransactionStatus().value()));
            first = false;
        }
        if (isSetStatusCode()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("StatusCode"));
            json.append(" : ");
            json.append(quoteJSON(getStatusCode()));
            first = false;
        }
        if (isSetStatusMessage()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("StatusMessage"));
            json.append(" : ");
            json.append(quoteJSON(getStatusMessage()));
            first = false;
        }
        if (isSetSenderName()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("SenderName"));
            json.append(" : ");
            json.append(quoteJSON(getSenderName()));
            first = false;
        }
        if (isSetSenderEmail()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("SenderEmail"));
            json.append(" : ");
            json.append(quoteJSON(getSenderEmail()));
            first = false;
        }
        if (isSetCallerName()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("CallerName"));
            json.append(" : ");
            json.append(quoteJSON(getCallerName()));
            first = false;
        }
        if (isSetRecipientName()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("RecipientName"));
            json.append(" : ");
            json.append(quoteJSON(getRecipientName()));
            first = false;
        }
        if (isSetRecipientEmail()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("RecipientEmail"));
            json.append(" : ");
            json.append(quoteJSON(getRecipientEmail()));
            first = false;
        }
        if (isSetRelatedTransaction()) {
            if (!first) json.append(", ");
            json.append("\"RelatedTransaction\" : [");
            java.util.List<RelatedTransaction> relatedTransactionList = getRelatedTransaction();
            int relatedTransactionListIndex = 0;
            for (RelatedTransaction relatedTransaction : relatedTransactionList) {
                if (relatedTransactionListIndex > 0) json.append(", ");
                json.append("{");
                json.append("");
                json.append(relatedTransaction.toJSONFragment());
                json.append("}");
                first = false;
                ++relatedTransactionListIndex;
            }
            json.append("]");
        }
        if (isSetStatusHistory()) {
            if (!first) json.append(", ");
            json.append("\"StatusHistory\" : [");
            java.util.List<StatusHistory> statusHistoryList = getStatusHistory();
            int statusHistoryListIndex = 0;
            for (StatusHistory statusHistory : statusHistoryList) {
                if (statusHistoryListIndex > 0) json.append(", ");
                json.append("{");
                json.append("");
                json.append(statusHistory.toJSONFragment());
                json.append("}");
                first = false;
                ++statusHistoryListIndex;
            }
            json.append("]");
        }
        return json.toString();
    }

    /**
     *
     * Quote JSON string
     */
    private String quoteJSON(String string) {
        StringBuffer sb = new StringBuffer();
        sb.append("\"");
        int length = string.length();
        for (int i = 0; i < length; ++i) {
            char c = string.charAt(i);
            switch (c) {
            case '"':
                sb.append("\\\"");
                break;
            case '\\':
                sb.append("\\\\");
                break;
            case '/':
                sb.append("\\/");
                break;
            case '\b':
                sb.append("\\b");
                break;
            case '\f':
                sb.append("\\f");
                break;
            case '\n':
                sb.append("\\n");
                break;
            case '\r':
                sb.append("\\r");
                break;
            case '\t':
                sb.append("\\t");
                break;
            default:
                if (c <  ' ') {
                    sb.append("\\u" + String.format("%03x", Integer.valueOf(c)));
                } else {
                sb.append(c);
            }
        }
        }
        sb.append("\"");
        return sb.toString();
    }


}
