
package com.amazonaws.fps.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CreditInstrumentId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AdjustmentAmount" type="{http://fps.amazonaws.com/doc/2008-09-17/}Amount" minOccurs="0"/>
 *         &lt;element name="CallerReference" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CallerDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * Generated by AWS Code Generator
 * <p/>
 * Tue Sep 29 03:25:23 PDT 2009
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "creditInstrumentId",
    "adjustmentAmount",
    "callerReference",
    "callerDescription"
})
@XmlRootElement(name = "WriteOffDebtRequest")
public class WriteOffDebtRequest {

    @XmlElement(name = "CreditInstrumentId")
    protected String creditInstrumentId;
    @XmlElement(name = "AdjustmentAmount")
    protected Amount adjustmentAmount;
    @XmlElement(name = "CallerReference")
    protected String callerReference;
    @XmlElement(name = "CallerDescription")
    protected String callerDescription;

    /**
     * Default constructor
     * 
     */
    public WriteOffDebtRequest() {
        super();
    }

    /**
     * Value constructor
     * 
     */
    public WriteOffDebtRequest(final String creditInstrumentId, final Amount adjustmentAmount, final String callerReference, final String callerDescription) {
        this.creditInstrumentId = creditInstrumentId;
        this.adjustmentAmount = adjustmentAmount;
        this.callerReference = callerReference;
        this.callerDescription = callerDescription;
    }

    /**
     * Gets the value of the creditInstrumentId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreditInstrumentId() {
        return creditInstrumentId;
    }

    /**
     * Sets the value of the creditInstrumentId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreditInstrumentId(String value) {
        this.creditInstrumentId = value;
    }

    public boolean isSetCreditInstrumentId() {
        return (this.creditInstrumentId!= null);
    }

    /**
     * Gets the value of the adjustmentAmount property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getAdjustmentAmount() {
        return adjustmentAmount;
    }

    /**
     * Sets the value of the adjustmentAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setAdjustmentAmount(Amount value) {
        this.adjustmentAmount = value;
    }

    public boolean isSetAdjustmentAmount() {
        return (this.adjustmentAmount!= null);
    }

    /**
     * Gets the value of the callerReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCallerReference() {
        return callerReference;
    }

    /**
     * Sets the value of the callerReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCallerReference(String value) {
        this.callerReference = value;
    }

    public boolean isSetCallerReference() {
        return (this.callerReference!= null);
    }

    /**
     * Gets the value of the callerDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCallerDescription() {
        return callerDescription;
    }

    /**
     * Sets the value of the callerDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCallerDescription(String value) {
        this.callerDescription = value;
    }

    public boolean isSetCallerDescription() {
        return (this.callerDescription!= null);
    }

    /**
     * Sets the value of the CreditInstrumentId property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public WriteOffDebtRequest withCreditInstrumentId(String value) {
        setCreditInstrumentId(value);
        return this;
    }

    /**
     * Sets the value of the AdjustmentAmount property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public WriteOffDebtRequest withAdjustmentAmount(Amount value) {
        setAdjustmentAmount(value);
        return this;
    }

    /**
     * Sets the value of the CallerReference property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public WriteOffDebtRequest withCallerReference(String value) {
        setCallerReference(value);
        return this;
    }

    /**
     * Sets the value of the CallerDescription property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public WriteOffDebtRequest withCallerDescription(String value) {
        setCallerDescription(value);
        return this;
    }
    


    /**
     *
     * JSON fragment representation of this object
     *
     * @return JSON fragment for this object. Name for outer
     * object expected to be set by calling method. This fragment
     * returns inner properties representation only
     *
     */
    protected String toJSONFragment() {
        StringBuffer json = new StringBuffer();
        boolean first = true;
        if (isSetCreditInstrumentId()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("CreditInstrumentId"));
            json.append(" : ");
            json.append(quoteJSON(getCreditInstrumentId()));
            first = false;
        }
        if (isSetAdjustmentAmount()) {
            if (!first) json.append(", ");
            json.append("\"AdjustmentAmount\" : {");
            Amount  adjustmentAmount = getAdjustmentAmount();


            json.append(adjustmentAmount.toJSONFragment());
            json.append("}");
            first = false;
        }
        if (isSetCallerReference()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("CallerReference"));
            json.append(" : ");
            json.append(quoteJSON(getCallerReference()));
            first = false;
        }
        if (isSetCallerDescription()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("CallerDescription"));
            json.append(" : ");
            json.append(quoteJSON(getCallerDescription()));
            first = false;
        }
        return json.toString();
    }

    /**
     *
     * Quote JSON string
     */
    private String quoteJSON(String string) {
        StringBuffer sb = new StringBuffer();
        sb.append("\"");
        int length = string.length();
        for (int i = 0; i < length; ++i) {
            char c = string.charAt(i);
            switch (c) {
            case '"':
                sb.append("\\\"");
                break;
            case '\\':
                sb.append("\\\\");
                break;
            case '/':
                sb.append("\\/");
                break;
            case '\b':
                sb.append("\\b");
                break;
            case '\f':
                sb.append("\\f");
                break;
            case '\n':
                sb.append("\\n");
                break;
            case '\r':
                sb.append("\\r");
                break;
            case '\t':
                sb.append("\\t");
                break;
            default:
                if (c <  ' ') {
                    sb.append("\\u" + String.format("%03x", Integer.valueOf(c)));
                } else {
                sb.append(c);
            }
        }
        }
        sb.append("\"");
        return sb.toString();
    }


}
